# Generated by Django 5.1.3 on 2025-11-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agua', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='agua.cashbox'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.cashconcept'),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='agua.cashbox'),
        ),
        migrations.AddField(
            model_name='customer',
            name='calle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agua.calle'),
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='agua.category'),
        ),
        migrations.AddField(
            model_name='dailycashreport',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='agua.cashbox'),
        ),
        migrations.AddField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='agua.customer'),
        ),
        migrations.AddField(
            model_name='debtdetail',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.cashconcept'),
        ),
        migrations.AddField(
            model_name='debtdetail',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='agua.debt'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='agua.customer'),
        ),
        migrations.AddField(
            model_name='invoiceconcept',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.cashconcept'),
        ),
        migrations.AddField(
            model_name='invoiceconcept',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_concepts', to='agua.invoice'),
        ),
        migrations.AddField(
            model_name='invoicedebt',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='agua.debt'),
        ),
        migrations.AddField(
            model_name='invoicedebt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_debts', to='agua.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='agua.cashbox'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='agua.invoice'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='invoice_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='agua.invoicepayment'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reading',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='agua.customer'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='agua.reading'),
        ),
        migrations.AddField(
            model_name='readinggeneration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calle',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calles', to='agua.via'),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='agua.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agua.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycashreport',
            unique_together={('cashbox', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='invoicedebt',
            unique_together={('invoice', 'debt')},
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('customer', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='readinggeneration',
            unique_together={('period',)},
        ),
    ]
