# Generated by Django 5.1.3 on 2025-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_fixed_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
