# Generated by Django 5.1.3 on 2025-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_category_price_fixed_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='period_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='period_start',
            field=models.DateField(null=True),
        ),
    ]
