# Generated by Django 5.1.3 on 2025-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0004_reading_period_end_reading_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='codigo',
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
