# Generated by Django 5.1.3 on 2025-11-25 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0005_alter_zona_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agua.zona'),
        ),
    ]
