# Generated by Django 5.1.3 on 2025-11-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0006_calle_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='connection_type',
            field=models.CharField(choices=[('new', 'Conexión nueva'), ('old', 'Conexión antigua')], default='new', max_length=10),
        ),
    ]
