# Generated by Django 5.1.3 on 2025-12-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0007_customer_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_clean',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
