# Generated by Django 5.1.3 on 2025-12-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0008_category_price_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='billing_mode',
            field=models.CharField(choices=[('per_unit', 'Por consumo real'), ('fixed_until_max', 'Fijo hasta máximo')], default='per_unit', max_length=20),
        ),
    ]
