# Generated by Django 5.1.3 on 2025-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0009_category_billing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='total_clean',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
