# Generated by Django 5.1.3 on 2025-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0010_reading_total_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='igv',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='reading',
            name='total_igv',
            field=models.IntegerField(default=18),
        ),
    ]
