# Generated by Django 5.1.3 on 2025-12-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0011_reading_igv_reading_total_igv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='total_igv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
