# Generated by Django 5.1.3 on 2025-12-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0012_alter_reading_total_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='sub_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
