# Generated by Django 5.1.3 on 2025-12-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0013_reading_sub_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_igv_category', models.BooleanField(default=False, verbose_name='Incluir IGV en tarifas')),
            ],
        ),
    ]
