# Generated by Django 5.1.3 on 2025-12-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0014_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
