# Generated by Django 5.1.3 on 2025-12-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0016_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
