# Generated by Django 5.1.3 on 2025-12-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0017_delete_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_origin',
            field=models.CharField(choices=[('counter', 'Presencial'), ('gateway', 'Pasarela de pagos')], default='counter', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
