# Generated by Django 5.1.3 on 2025-12-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0018_invoice_payment_origin_invoice_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='enable_online_payments',
            field=models.BooleanField(default=False, verbose_name='Habilitar pagos online'),
        ),
        migrations.AddField(
            model_name='config',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mercado Pago Access Token'),
        ),
        migrations.AddField(
            model_name='config',
            name='mp_public_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mercado Pago Public Key'),
        ),
    ]
