# Generated by Django 5.1.3 on 2025-12-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0019_config_enable_online_payments_config_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
