# Generated by Django 5.1.3 on 2026-01-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0020_alter_customer_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='user',
        ),
        migrations.AddField(
            model_name='cashbox',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
