# Generated by Django 5.1.3 on 2026-01-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0021_remove_cashbox_user_cashbox_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggeneration',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
