# Generated by Django 5.1.3 on 2026-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0022_alter_readinggeneration_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashconcept',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashconcept',
            name='is_master_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashconcept',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cashconcept',
            name='system_key',
            field=models.CharField(blank=True, choices=[('price_water', 'Precio agua'), ('price_sewer', 'Precio alcantarillado'), ('price_fixed_charge', 'Precio cargo fijo'), ('price_clean', 'Precio limpieza'), ('price_igv', 'Precio Igv')], db_index=True, max_length=30, null=True),
        ),
    ]
