# Generated by Django 5.1.3 on 2026-04-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0023_cashconcept_is_master_cashconcept_is_master_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='distrito',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='provincia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
