# Generated by Django 5.1.3 on 2026-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0024_customer_distrito_customer_provincia_customer_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_type',
            field=models.CharField(choices=[('both', 'Agua y desagüe'), ('water', 'Solo agua'), ('sewer', 'Solo desagüe')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='supply_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
