# Generated by Django 5.1.3 on 2026-04-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0025_customer_billing_type_customer_supply_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_refinanced',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DebtRefinancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DebtRefinancingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.debt')),
                ('refinancing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='agua.debtrefinancing')),
            ],
        ),
        migrations.CreateModel(
            name='RefinancingInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('refinancing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='agua.debtrefinancing')),
            ],
        ),
    ]
