# Generated by Django 5.1.3 on 2026-04-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0026_debt_is_refinanced_debtrefinancing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.refinancinginstallment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_installments', to='agua.invoice')),
            ],
        ),
    ]
