# Generated by Django 5.1.3 on 2026-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0027_invoiceinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido'), ('low', 'Baja'), ('observed', 'Observado')], default='active', max_length=15),
        ),
    ]
