# Generated by Django 5.1.3 on 2026-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0028_customer_observation_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_record',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='record_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
