# Generated by Django 5.1.3 on 2026-04-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0029_customer_date_of_record_customer_record_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En ejecución'), ('completed', 'Completado')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Deuda pendiente', max_length=255)),
                ('scheduled_date', models.DateField()),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('executed', 'Ejecutado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('executed', 'Cortado'), ('paid', 'Pagó en campo'), ('not_found', 'No ubicado'), ('postponed', 'Postergado')], max_length=20, null=True)),
                ('executed_by', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuts', to='agua.cutbatch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='agua.customer')),
                ('debts', models.ManyToManyField(blank=True, to='agua.debt')),
            ],
        ),
    ]
