# Generated by Django 5.1.3 on 2026-05-07 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0030_cutbatch_servicecut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermeter',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='watermeter',
            name='installation_date',
        ),
        migrations.AddField(
            model_name='reading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agua.watermeter'),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watermeter',
            name='diameter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('installed', 'Instalado'), ('removed', 'Retirado'), ('damaged', 'Dañado'), ('maintenance', 'Mantenimiento')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido'), ('observed', 'Observado'), ('cut', 'Cortado'), ('low', 'Baja')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agua.zona'),
        ),
        migrations.CreateModel(
            name='MeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField()),
                ('removal_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.customer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agua.watermeter')),
            ],
        ),
    ]
