# Generated by Django 5.1.3 on 2026-05-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0030_cutbatch_servicecut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido'), ('observed', 'Observado'), ('cut', 'Cortado'), ('low', 'Baja')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agua.zona'),
        ),
    ]
