# Generated by Django 5.1.3 on 2026-05-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0031_alter_customer_state_alter_customer_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermeter',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='watermeter',
            name='installation_date',
        ),
        migrations.AddField(
            model_name='watermeter',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watermeter',
            name='diameter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('installed', 'Instalado'), ('removed', 'Retirado'), ('damaged', 'Dañado'), ('maintenance', 'Mantenimiento')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='MeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField()),
                ('removal_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.customer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='agua.watermeter')),
            ],
        ),
    ]
