# Generated by Django 5.1.3 on 2026-05-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0031_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agua.zona'),
        ),
    ]
