# Generated by Django 5.1.3 on 2026-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0031_remove_watermeter_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source_type',
            field=models.CharField(choices=[('well', 'Pozo'), ('company', 'Empresa')], default='company', max_length=20),
        ),
    ]
