# Generated by Django 5.1.3 on 2026-05-05 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0031_remove_watermeter_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agua.watermeter'),
        ),
    ]
