# Generated by Django 5.1.3 on 2026-05-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0032_customer_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_rate_sewer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
