# Generated by Django 5.1.3 on 2026-05-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0034_reading_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
