# Generated by Django 5.1.3 on 2026-05-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0035_invoice_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='predio',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agua.zona'),
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='agua.zona')),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
                'unique_together': {('zona', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agua.manzana'),
        ),
    ]
