# Generated by Django 5.1.3 on 2026-05-22 03:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0036_customer_predio_alter_customer_zona_manzana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refinancinginstallment',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='debtrefinancing',
            name='installments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='debtrefinancing',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtrefinancing',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AddField(
            model_name='debtrefinancing',
            name='total_amount_with_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refinancinginstallment',
            name='capital_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refinancinginstallment',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 22, 3, 10, 59, 750437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refinancinginstallment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtrefinancing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinancings', to='agua.customer'),
        ),
        migrations.AlterField(
            model_name='refinancinginstallment',
            name='refinancing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_details', to='agua.debtrefinancing'),
        ),
    ]
