# Generated by Django 5.1.3 on 2026-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0037_rename_amount_refinancinginstallment_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('estimated', 'Estimada'), ('revised', 'Corregida'), ('no_access', 'Sin acceso')], default='normal', max_length=20),
        ),
    ]
