# Generated by Django 5.1.3 on 2026-05-28 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0039_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtrefinancing',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtrefinancing',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtrefinancingdetail',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agua.debt'),
        ),
    ]
