# Generated by Django 5.1.3 on 2026-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0041_servicecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(choices=[('debt', 'Servicio de Agua'), ('concept', 'Cargo Adicional'), ('fractionate', 'Cuota de Fraccionamiento')], default='debt', max_length=100),
        ),
    ]
