# Generated by Django 5.1.3 on 2026-06-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0042_alter_invoice_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='igv',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='total_clean',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='total_fixed_charge',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='total_igv',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido'), ('cut', 'Cortado'), ('low', 'Baja')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(choices=[('debt', 'Servicio de Agua'), ('concept', 'Cargo por Concepto'), ('fractionate', 'Cuota de Fraccionamiento')], default='debt', max_length=100),
        ),
    ]
