# Generated by Django 5.1.3 on 2026-06-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0043_remove_reading_igv_remove_reading_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconcept',
            name='system_key',
            field=models.CharField(blank=True, choices=[('price_water', 'Precio agua'), ('price_sewer', 'Precio alcantarillado'), ('price_fixed_charge', 'Precio cargo fijo'), ('price_clean', 'Precio limpieza'), ('price_igv', 'Precio Igv'), ('price_maintenance', 'Precio Mantenimiento')], db_index=True, max_length=30, null=True),
        ),
    ]
