# Generated by Django 5.1.3 on 2026-06-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0044_alter_cashconcept_system_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtrefinancing',
            name='type',
            field=models.CharField(choices=[('debt', 'Deuda'), ('service', 'Servicio')], default='debt', max_length=20),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='is_refinanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('refinanced', 'Refinanciado'), ('paid', 'Pagado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceRefinancingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refinancing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='agua.debtrefinancing')),
                ('service_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agua.servicecharge')),
            ],
        ),
    ]
