# Generated by Django 5.1.3 on 2026-07-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0045_debtrefinancing_type_servicecharge_is_refinanced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtrefinancing',
            name='type',
            field=models.CharField(choices=[('debt', 'Deuda'), ('service', 'Servicio'), ('mixed', 'Mixto')], default='debt', max_length=20),
        ),
    ]
