# Generated by Django 5.1.3 on 2026-08-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0046_alter_debtrefinancing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_all', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='agua.category')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='agua.zona')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryZoneBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agua.manzana')),
                ('category_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_blocks', to='agua.categoryzone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoryzone',
            constraint=models.UniqueConstraint(fields=('zone',), name='unique_category_per_zone'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryzoneblock',
            unique_together={('category_zone', 'block')},
        ),
    ]
