# Generated by Django 5.1.3 on 2026-08-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0047_categoryzone_categoryzoneblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecut',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='agua.cutbatch'),
        ),
    ]
