# Generated by Django 5.1.3 on 2026-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0050_alter_servicecut_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, help_text='ID del usuario del schema public', null=True)),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('cancel', 'Anulación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('other', 'Otro')], db_index=True, max_length=20)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
