# Generated by Django 5.1.3 on 2026-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0051_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_special_rate',
            field=models.BooleanField(default=False, verbose_name='Tiene tarifa especial'),
        ),
        migrations.AddField(
            model_name='customer',
            name='special_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto especial'),
        ),
    ]
