# Generated by Django 5.1.3 on 2026-01-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='grace_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_due_date',
            field=models.DateField(default='2025-12-01'),
            preserve_default=False,
        ),
    ]
