# Generated by Django 5.1.3 on 2026-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_client_grace_days_client_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=50)),
                ('zona_id', models.IntegerField()),
                ('period', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
