# Generated by Django 5.1.3 on 2026-05-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_receiptbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptbatch',
            name='zona_id',
        ),
        migrations.AddField(
            model_name='receiptbatch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptbatch',
            name='ticket',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptbatch',
            name='type',
            field=models.CharField(choices=[('masivo', 'Masivo'), ('zona', 'Zona'), ('calle', 'Calle')], default='masivo', max_length=20),
        ),
    ]
