# Generated by Django 5.1.3 on 2026-05-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_remove_receiptbatch_zona_id_receiptbatch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptbatch',
            name='zona',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
