# Generated by Django 5.1.3 on 2026-05-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_receiptbatch_zona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptbatch',
            old_name='zona',
            new_name='zona_id',
        ),
    ]
