# Generated by Django 5.1.3 on 2026-09-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_module_options_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_readonly',
            field=models.BooleanField(default=False, verbose_name='Solo lectura'),
        ),
    ]
